name: Cypress Tests
on: [push]

jobs:
  mrb-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          tags: mrbeam_plugin:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mrbeam_plugin
          path: /tmp/image.tar

  ui-chrome-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: cypress/browsers:node12.18.3-chrome87-ff82
      options: --add-host=mrbeam-plugin.org:host-gateway
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    needs: mrb-docker
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 1, 2, 3, 4, 5 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: mrbeam_plugin
          path: /tmp
      - name: Load Docker image
        run: |
          apt-get --allow-releaseinfo-change update
          apt-get install docker.io -y
          cat /etc/hosts
          docker load --input /tmp/image.tar
          docker network ls
          BRIDGE_NETWORK_ID=$(docker network ls --filter=name=github_network_ --format="{{.ID}}")
          echo $BRIDGE_NETWORK_ID
          docker run --name mrbeam-plugin -d -p5002:5000 mrbeam_plugin
          docker image ls -a
          docker inspect -f '{{ .NetworkSettings.Networks }}' $(docker ps -q)
          docker inspect -f '{{ .NetworkSettings.IPAddress }}' $(docker ps -q)

          sleep 15
          docker ps -a
          docker logs mrbeam-plugin
#      - run: |
#          envsubst < ./cypress/fixtures/test-data.template.json > ./cypress/fixtures/test-data.json
      - name: Run Cypress e2e - Chrome
        uses: cypress-io/github-action@v4
        with:
#          install: false
          wait-on: "http://mrbeam-plugin.org:5002/"
#          wait-on-timeout: 300
          browser: chrome
          config-file: cypress.config.js
#          parallel: true
#          group: 'UI - Chrome'
#          spec: cypress/e2e/*
          command: yarn ts-node scripts/cypress-ci-run.ts
        env:
          TOTAL_RUNNERS: 5
          THIS_RUNNER: ${{ matrix.containers }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Run Cypress e2e tests
#        uses: cypress-io/github-action@v4
#        with:
#          # we have already installed all dependencies above
#          install: false
#          # build: yarn build
#          start: yarn test:server
#          wait-on: 'http://localhost:3001'
#          command: yarn ts-node scripts/cypress-ci-run.ts
#        env:
#          # the number of containers in the job matrix
#          TOTAL_RUNNERS: 5
#          THIS_RUNNER: ${{ matrix.containers }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JUnit reports
        uses: actions/upload-artifact@v1
        # Only capture images on failure
        if: failure()
        with:
          name: cypress-report
          path: cypress/results


