name: E2E on Chrome
on: [push]
#  push:
#    branches:
#      - alpha
#      - beta
#      - stable
#      - mrbeam2-beta
#      - mrbeam2-stable
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3  # Cache dependencies to speed up process
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: cypress-io/github-action@v4
        with:
          start: npm run docker:build-and-run
          wait-on: "http://localhost:5002/"
          wait-on-timeout: 360
          browser: chrome
          config-file: cypress.config.js
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Merge reports
        run: npm run merge-reports
      - name: Import reports in Xray
        run: echo todo

