name: Cypress Tests
on: [push]

env:
  CYPRESS_TEST_USER_EMAIL: "dev@mr-beam.org"
  CYPRESS_TEST_USER_PASSWORD: "a"
  MRBEAM_PLUGIN_URL: "http://plugin-address.org:5002/"
  MRBEAM_PLUGIN_DOMAIN_NAME: "plugin-address.org"

jobs:
  mrb-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          tags: mrbeam_plugin:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mrbeam_plugin
          path: /tmp/image.tar

  ui-chrome-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: cypress/browsers:node16.17.0-chrome106
      options: --add-host={{ env.MRBEAM_PLUGIN_DOMAIN_NAME }}:host-gateway
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    needs: mrb-docker
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 0, 1, 2, 3, 4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: mrbeam_plugin
          path: /tmp
      - name: Load Docker image
        run: |
          apt-get --allow-releaseinfo-change update
          apt-get install docker.io -y
          docker load --input /tmp/image.tar
          docker run --name mrbeam-plugin -d -p5002:5000 mrbeam_plugin
      - run: |
          envsubst < ./cypress/fixtures/test-data.template.json > ./cypress/fixtures/test-data.json
          envsubst < ./cypress.config-template.js > ./cypress.config.js
      - name: Run Cypress e2e - Chrome
        uses: cypress-io/github-action@v4
        with:
          wait-on: ${{ env.MRBEAM_PLUGIN_URL }}
          browser: chrome
          config-file: cypress.config.js
          command: yarn ts-node cypress/scripts/cypress-ci-run.ts
        env:
          TOTAL_RUNNERS: 5
          THIS_RUNNER: ${{ matrix.containers }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JUnit reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: cypress-report
          path: cypress/results
