name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - alpha
      - beta
      - stable
      - mrbeam2-beta
      - mrbeam2-stable
  pull_request:
    types: [ opened, synchronize, reopened ]
#  push:
#    branches:
#      - alpha
#      - beta
#      - stable
#      - mrbeam2-beta
#      - mrbeam2-stable
#  pull_request:
#    types: [opened, synchronize, reopened]
jobs:
  testmain:
    name: Test Main
    runs-on: ubuntu-latest
    steps:
      - name: Echo python version main
        run: |
          echo LALALALA ${{ inputs.python_v }}

  build:
    uses: mrbeam/MrBeamPlugin/.github/workflows/build.yml@feature/SW-274-github-actions-setup-and-test
    with:
      python_v: "2.7"
